---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# TACforecasting 

This package provides functions to help with forecasting attendant care hours for the Transport Accident Commission.

## Installation

```{r, eval = FALSE}
# First install the dependencies
install.packages(c("tsibble","fabletools","abind","distributional","dplyr",
	"forcats","forecast","furrr","ggplot2","hts","janitor","lubridate",
  "MASS","readr","stringr","tibble","tidyr","tsbox","remotes"))
# Then install this package
remotes::install_github("robjhyndman/TACforecasting")
```

## Example

The data included in the package and in this example has been randomly generated. No real data is included in this repository.

```{r, message=FALSE}
library(TACforecasting)
library(dplyr)
library(ggplot2)
```

```r
# Read data
group_costs <- read_tac_data(
  claims_file = "data-raw/T086_claim_header.csv",
  costs_file = "data-raw/T086_attendant_care_hours.csv"
)
```

```{r}
# Plot total hours by billing period
plot_total_hours(group_costs)

# Plot total hours per age group by billing period
plot_total_hours(group_costs, age_group, include_average = FALSE) +
   ggtitle("Hours by age group in each billing period")

# Plot total hours per injury group by billing period
plot_total_hours(group_costs, injury_group, include_average = FALSE) +
   ggtitle("Hours by injury group in each billing period")
```


```{r}
# Compute forecasts of total hours by age group and injury group
# Keep back 2022 as test set
fable_forecasts_hours <- group_costs |> 
	filter(billing_period <= as.Date("2021-12-31")) |> 
	get_forecasts(h = 13, nsim = 200)
```

```{r}
# Plot forecasts of total hours
plot_forecasts(fable_forecasts_hours, group_costs)

# Plot forecasts of total hours by age group
plot_forecasts(fable_forecasts_hours, group_costs, show_age_group = "20-34") +
   ggtitle("Forecasts of total hours for 20-34 year olds")

# Plot forecasts of total hours by injury group
plot_forecasts(fable_forecasts_hours, group_costs, show_injury_group = "NONCAT") +
   ggtitle("Forecasts of total hours from NONCAT injuries claims")
```

```{r message=FALSE, warning=FALSE}
# Compute accuracy statistics on the 2022 test set
tac_accuracy(fable_forecasts_hours, group_costs)
# Compute accuracy statistics on a rolling origin
# (This takes a long time to run)
tscv_accuracy(group_costs, h = 13, nsim = 200, init = 195, step = 6) |> 
  filter(!is.na(RMSE), h <= 24) |>
  summarise(
    RMSE = sqrt(mean(RMSE^2)),
    MAE = mean(MAE),
    MAPE = mean(MAPE),
    Coverage = 100*mean(coverage),
    CRPS = mean(CRPS),
    .by = h
  ) 
```
